### ISSUE TITLE
I would like to see functionality added to allow HTML development and deployment.

### ISSUE THREAD

**Issue by YukiFujisawa** [google/aside#17]
## Feature Requests

To be able to develop HTML/CSS with VSCode and ASIDE.

## Benefits

VSCode's HTML/CSS development will be supported by Github Copilot, etc.

## Note

If there is a way to achieve this in the current situation, we would appreciate it if you could let us know.

**Comment by paranerd** [comment]
I'm not sure I fully understand your request.
Could you please elaborate?

**Comment by YukiFujisawa** [comment]
@paranerd Thank you for your reply.

For example, I would like to develop the following "Serve HTML as a web app" with ASIDE.

https://developers.google.com/apps-script/guides/html?hl=ja#index.html

For example, if test.html is placed in src, it will be output to dist and can be deployed to GAS.

![スクリーンショット 2023-07-18 7 05 55](https://github.com/google/aside/assets/10007402/3c2e02b5-3cf2-4284-b849-920c78de1194)

**Comment by echom** [comment]
@YukiFujisawa I am currently working on a AppsScript webapp based on ASIDE. The base project generated by ASIDE needs a couple of modifications but it's generally feasible. I'll set up a feature branch soon with my ideas.

**Comment by paranerd** [comment]
In the meantime, if you just want to have the *.html uploaded (to deploy manually after), you could just edit your `package.json` scripts like this:

```json
"scripts": {
    ...
    "build": "npm run clean && npm run bundle && npm run copy-static",
    "copy-static": "mkdirp dist/static && ncp src/static/ dist/static"
}
```

**Comment by YukiFujisawa** [comment]
@paranerd Thank you for the very useful advice!
I will try the above method as soon as possible.

**Comment by YukiFujisawa** [comment]
@paranerd I am happy to report that I was able to deploy successfully with this fix.

```diff
diff --git a/package.json b/package.json
index 67d80eb..ebabdf0 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,8 @@
     "clean": "rimraf build dist",
     "lint": "npm run license && eslint --fix --no-error-on-unmatched-pattern src/ test/",
     "bundle": "rollup --no-treeshake -c rollup.config.mjs",
-    "build": "npm run clean && npm run bundle && ncp appsscript.json dist/appsscript.json",
+    "build": "npm run clean && npm run bundle && ncp appsscript.json dist/appsscript.json && npm run copy-static",
+    "copy-static": "mkdirp dist/static && ncp src/static/ dist/static",
     "license": "license-check-and-add add -f license-config.json",
     "test": "jest test/ --passWithNoTests --detectOpenHandles",
```
